dist: xenial
language: python
jobs:
  include:
    - python:
        - 3.7
      install:
        - pip install -e .
        - pip install -r requirements-dev.txt
      script:
        - pytest --cov=misago
      after_success:
        - coveralls
    - name: "lint"
      python: 3.7
      install:
        - pip install -U pip setuptools
        - pip install -e .
        - pip install -r requirements-dev.txt
      script:
        - pylint misago setup.py
        - mypy misago --ignore-missing-imports
        - black --check misago