dist: xenial
language: python
addons:
  postgresql: "10"
  apt:
    packages:
      - postgresql-10
      - postgresql-client-10
env:
  global:
    - PGPORT=5433
    - MISAGO_DATABASE_URL=postgresql://localhost:5433/travis_ci_test?user=postgres
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
jobs:
  include:
    - python:
        - 3.7
      install:
        - pip install -e .
        - pip install -r requirements-dev.txt
      script:
        - pytest --cov=misago
      after_success:
        - coveralls
    - name: "lint"
      python: 3.7
      install:
        - pip install -U pip setuptools
        - pip install -e .
        - pip install -r requirements-dev.txt
      script:
        - pylint misago setup.py
        - mypy misago --ignore-missing-imports
        - black --check misago